version: 0.2

phases:
  install:
    commands:
      - yum install nodejs16
  pre_build:
    commands:
      - npm i -g @angular/cli
      - npm install --force
  build:
    commands:
      - ng build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/pet-app-ng